<?php

/**
 * @file
 * Contains d324_ace_paragraph_behaviors.module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\paragraphs\ParagraphInterface;
use Drupal\d324_ace_paragraph_behaviors\Plugin\paragraphs\Behavior\AceParagraphsStylesBehavior;


/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function d324_ace_paragraph_behaviors_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  $paragraph = $variables['elements']['#paragraph'];
  if ($paragraph->getParagraphType()->hasEnabledBehaviorPlugin('ace_paragraphs_styles')) {
    if ($templates = $paragraph->getBehaviorSetting('ace_paragraphs_styles', 'styles')) {
      foreach ($templates as $group_name => $template) {
        $group_name = str_replace('-', '_', $group_name);
        $template = str_replace('-', '_', $template);
        $suggestions[] = 'paragraph__' . $paragraph->bundle() . '__' . $group_name . '__' . $template;
      }
      return $suggestions;
    }
  }
}

/**
 * * Implements hook_modules_installed().
 */
function d324_ace_paragraph_behaviors_modules_installed($modules) {
  \Drupal::service('d324_ace_paragraph_behaviors.style_discovery')->reset();
}

/**
 * * Implements hook_themes_installed().
 */
function d324_ace_paragraph_behaviors_themes_installed($themes) {
  \Drupal::service('d324_ace_paragraph_behaviors.style_discovery')->reset();
}

/**
 * * Implements hook_themes_uninstalled().
 */
function d324_ace_paragraph_behaviors_themes_uninstalled($themes) {
  \Drupal::service('d324_ace_paragraph_behaviors.style_discovery')->reset();
}
